version: '3'

networks:
  basic:

volumes:
  redis-data:
  credentials:
  contracts:


services:
  scrum-dao:
    image: krabradosty/scrum-dao
    restart: always
    environment:
      - NODE_ENV=stage
      - LOG_LEVEL=debug
    ports:
      - "127.0.0.1:8021:8021"
    volumes:
      - "credentials:/src/credentials/"
      - "contracts:/src/build/contracts/"
    networks:
      - basic
    depends_on:
      - redis

  redis:
    image: redis:3.2
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - 6379
    volumes:
        - "redis-data:/data"
    networks:
      - basic
